use crate::{
    Envelope, JoinRequestCreated, JoinRequestOffer, JoinRequestQr, JoinRequestStatus,
    PairingQrRecord,
};
use schemars::schema_for;
use serde_json::{Map, Value, json};
use std::{collections::BTreeMap, fs, io, path::Path};

pub struct GeneratedContracts {
    pub openapi: String,
    pub event_schema: String,
    pub typescript: String,
}

pub fn generate_contracts() -> GeneratedContracts {
    let envelope = serde_json::to_value(schema_for!(Envelope)).expect("Envelope schema serializes");
    let pairing =
        serde_json::to_value(schema_for!(PairingQrRecord)).expect("Pairing schema serializes");
    let join_created = serde_json::to_value(schema_for!(JoinRequestCreated))
        .expect("Join request created schema serializes");
    let join_qr = serde_json::to_value(schema_for!(JoinRequestQr))
        .expect("Join request QR schema serializes");
    let join_offer = serde_json::to_value(schema_for!(JoinRequestOffer))
        .expect("Join request offer schema serializes");
    let join_status = serde_json::to_value(schema_for!(JoinRequestStatus))
        .expect("Join request status schema serializes");
    let mut components = BTreeMap::new();
    components.extend(extract_components("Envelope", envelope));
    components.extend(extract_components("PairingQrRecord", pairing));
    components.extend(extract_components("JoinRequestCreated", join_created));
    components.extend(extract_components("JoinRequestQr", join_qr));
    components.extend(extract_components("JoinRequestOffer", join_offer));
    components.extend(extract_components("JoinRequestStatus", join_status));
    let mut component_value = serde_json::to_value(&components).expect("components serialize");
    rewrite_refs(&mut component_value);
    let openapi = pretty(
        &json!({"openapi":"3.1.0","info":{"title":"Peppy protocol","version":"1"},"paths":{},"components":{"schemas":component_value}}),
    );
    let mut event_schema =
        serde_json::to_value(schema_for!(Envelope)).expect("event schema serializes");
    event_schema["$schema"] = Value::String("https://json-schema.org/draft/2020-12/schema".into());
    let event_schema = pretty(&event_schema);
    let typescript =
        typescript_from_components(component_value.as_object().expect("components object"));
    GeneratedContracts {
        openapi,
        event_schema,
        typescript,
    }
}

fn extract_components(root_name: &str, mut schema: Value) -> BTreeMap<String, Value> {
    let definitions = schema.as_object_mut().and_then(|object| {
        object
            .remove("$defs")
            .or_else(|| object.remove("definitions"))
    });
    let mut root = schema.as_object().cloned().unwrap_or_default();
    root.remove("$schema");
    let mut result = BTreeMap::new();
    result.insert(root_name.into(), Value::Object(root));
    if let Some(definitions) = definitions.and_then(|value| value.as_object().cloned()) {
        result.extend(definitions);
    }
    result
}

fn rewrite_refs(value: &mut Value) {
    match value {
        Value::Object(object) => {
            if let Some(Value::String(reference)) = object.get_mut("$ref")
                && let Some(name) = reference
                    .strip_prefix("#/$defs/")
                    .or_else(|| reference.strip_prefix("#/definitions/"))
            {
                *reference = format!("#/components/schemas/{name}");
            }
            for child in object.values_mut() {
                rewrite_refs(child);
            }
        }
        Value::Array(items) => {
            for child in items {
                rewrite_refs(child);
            }
        }
        _ => {}
    }
}

pub fn all_schema_references_resolve(openapi: &Value) -> bool {
    fn visit(value: &Value, schemas: &Map<String, Value>) -> bool {
        match value {
            Value::Object(object) => {
                object
                    .get("$ref")
                    .and_then(Value::as_str)
                    .map(|reference| {
                        reference
                            .strip_prefix("#/components/schemas/")
                            .is_some_and(|name| schemas.contains_key(name))
                    })
                    .unwrap_or(true)
                    && object.values().all(|child| visit(child, schemas))
            }
            Value::Array(items) => items.iter().all(|child| visit(child, schemas)),
            _ => true,
        }
    }
    openapi
        .pointer("/components/schemas")
        .and_then(Value::as_object)
        .is_some_and(|schemas| visit(openapi, schemas))
}

fn typescript_from_components(schemas: &Map<String, Value>) -> String {
    let mut output = String::from("// Generated by peppy-protocol; do not edit.\n");
    for (name, schema) in schemas {
        output.push_str(&format!(
            "export type {} = {};\n",
            type_name(name),
            schema_to_ts(schema)
        ));
    }
    output
}

fn schema_to_ts(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference
            .rsplit('/')
            .next()
            .map(type_name)
            .unwrap_or_else(|| "unknown".into());
    }
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        return values
            .iter()
            .filter_map(Value::as_str)
            .map(|value| format!("'{}'", value.replace('\\', "\\\\").replace('\'', "\\'")))
            .collect::<Vec<_>>()
            .join(" | ");
    }
    for composition in ["anyOf", "oneOf", "allOf"] {
        if let Some(items) = schema.get(composition).and_then(Value::as_array) {
            return items
                .iter()
                .map(schema_to_ts)
                .collect::<Vec<_>>()
                .join(if composition == "allOf" { " & " } else { " | " });
        }
    }
    if let Some(kinds) = schema.get("type").and_then(Value::as_array) {
        return kinds
            .iter()
            .filter_map(Value::as_str)
            .map(json_type_to_ts)
            .collect::<Vec<_>>()
            .join(" | ");
    }
    let kind = schema.get("type").and_then(Value::as_str);
    match kind {
        Some("object") | None if schema.get("properties").is_some() => {
            let required = schema
                .get("required")
                .and_then(Value::as_array)
                .map(|items| {
                    items
                        .iter()
                        .filter_map(Value::as_str)
                        .collect::<std::collections::BTreeSet<_>>()
                })
                .unwrap_or_default();
            let properties = schema
                .get("properties")
                .and_then(Value::as_object)
                .map(|properties| {
                    properties
                        .iter()
                        .map(|(name, property)| {
                            format!(
                                "{}{}: {};",
                                ts_property_name(name),
                                if required.contains(name.as_str()) {
                                    ""
                                } else {
                                    "?"
                                },
                                schema_to_ts(property)
                            )
                        })
                        .collect::<Vec<_>>()
                        .join(" ")
                })
                .unwrap_or_default();
            format!("{{ {properties} }}")
        }
        Some("array") => format!(
            "{}[]",
            schema
                .get("items")
                .map(schema_to_ts)
                .unwrap_or_else(|| "unknown".into())
        ),
        Some(kind) => json_type_to_ts(kind),
        _ => "unknown".into(),
    }
}

fn json_type_to_ts(kind: &str) -> String {
    match kind {
        "string" => "string".into(),
        "integer" | "number" => "number".into(),
        "boolean" => "boolean".into(),
        "null" => "null".into(),
        _ => "unknown".into(),
    }
}

fn type_name(value: &str) -> String {
    value
        .chars()
        .filter(|character| character.is_ascii_alphanumeric() || *character == '_')
        .collect()
}
fn ts_property_name(value: &str) -> String {
    if value
        .chars()
        .all(|character| character.is_ascii_alphanumeric() || character == '_')
    {
        value.into()
    } else {
        format!("'{}'", value.replace('\'', "\\'"))
    }
}
fn pretty(value: &Value) -> String {
    serde_json::to_string_pretty(value).expect("schema JSON serializes") + "\n"
}

pub fn write_contracts(root: &Path, check: bool) -> io::Result<bool> {
    let generated = generate_contracts();
    let outputs = [
        (
            root.join("packages/contracts/openapi.json"),
            generated.openapi,
        ),
        (
            root.join("tests/fixtures/protocol/event.schema.json"),
            generated.event_schema,
        ),
        (
            root.join("packages/generated/src/protocol.ts"),
            generated.typescript,
        ),
    ];
    let mut matches = true;
    for (path, contents) in outputs {
        if fs::read_to_string(&path).ok().as_deref() != Some(contents.as_str()) {
            matches = false;
            if !check {
                if let Some(parent) = path.parent() {
                    fs::create_dir_all(parent)?;
                }
                fs::write(path, contents)?;
            }
        }
    }
    Ok(matches)
}
