#!/usr/bin/env node
import { cp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { catalog, nativeCatalog, desktopCatalog } from "../src/catalog.mjs";
import { kotlinNames, semanticTokens, swiftNames } from "../src/tokens.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const paths = {
  css: resolve(root, "packages/desktop-ui/src/peppy-tokens.css"),
  mark: resolve(root, "packages/mobile-design/assets/peppy-mark.svg"),
  appIcon: resolve(root, "packages/mobile-design/assets/peppy-app-icon.svg"),
  darkAppIcon: resolve(root, "packages/mobile-design/assets/peppy-app-icon-dark.svg"),
  tintedAppIcon: resolve(root, "packages/mobile-design/assets/peppy-app-icon-tinted.svg"),
  androidTokens: resolve(root, "apps/android/app/src/main/java/dev/peppy/mobile/ui/theme/PeppyTokens.kt"),
  androidStrings: resolve(root, "apps/android/app/src/main/res/values/strings_peppy.xml"),
  androidLogo: resolve(root, "apps/android/app/src/main/res/drawable/peppy_logo.xml"),
  androidForeground: resolve(root, "apps/android/app/src/main/res/drawable/ic_launcher_foreground.xml"),
  androidBackground: resolve(root, "apps/android/app/src/main/res/drawable/ic_launcher_background.xml"),
  androidMonochrome: resolve(root, "apps/android/app/src/main/res/drawable/ic_launcher_monochrome.xml"),
  androidIcon: resolve(root, "apps/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml"),
  androidRoundIcon: resolve(root, "apps/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml"),
  iosRoot: resolve(root, "apps/ios/PeppyMobile/Assets.xcassets/Contents.json"),
  iosTokens: resolve(root, "apps/ios/PeppyMobile/Design/PeppyTokens.swift"),
  iosStrings: resolve(root, "apps/ios/PeppyMobile/Peppy.xcstrings"),
  desktopCopy: resolve(root, "apps/desktop/src/generated/peppyCopy.ts"),
  iosLogo: resolve(root, "apps/ios/PeppyMobile/Assets.xcassets/PeppyLogo.imageset/peppy-logo.svg"),
  iosLogoContents: resolve(root, "apps/ios/PeppyMobile/Assets.xcassets/PeppyLogo.imageset/Contents.json"),
  iosIconContents: resolve(root, "apps/ios/PeppyMobile/Assets.xcassets/AppIcon.appiconset/Contents.json"),
  desktopLogo: resolve(root, "apps/desktop/public/peppy-logo.svg"),
  favicon: resolve(root, "apps/desktop/public/favicon.svg"),
};
const staticOutputs = Object.values(paths).filter(path => ![paths.css, paths.mark].includes(path));
const iconDir = resolve(root, "apps/desktop/src-tauri/icons");
const iosIconDir = resolve(root, "apps/ios/PeppyMobile/Assets.xcassets/AppIcon.appiconset");
const defaultIconFiles = ["128x128.png", "128x128@2x.png", "icon.png", "icon.ico", "icon.icns"];
// iOS 26 uses one universal 1024px image per appearance; Xcode derives device sizes.
const iosDefaultIcons = ["AppIcon-512@2x.png"];

function extractTheme(css, selector) {
  const start = css.indexOf(selector);
  if (start < 0) throw new Error(`Missing ${selector}`);
  const body = css.slice(start, css.indexOf("}", start));
  return Object.fromEntries([...body.matchAll(/--peppy-([\w-]+):\s*([^;]+);/g)].map(([, key, value]) => [key, value.trim()]));
}
function color(value) {
  const hex = value.replace(/^#/, "");
  if (/^[0-9a-f]{6}$/i.test(hex)) return `FF${hex.toUpperCase()}`;
  if (/^[0-9a-f]{3}$/i.test(hex)) return `FF${[...hex].map(char => char + char).join("").toUpperCase()}`;
  throw new Error(`Expected hex token, received ${value}`);
}
function selected(theme) {
  return Object.fromEntries(semanticTokens.map(key => {
    if (!theme[key]) throw new Error(`Missing --peppy-${key}`);
    return [key, color(theme[key])];
  }));
}
function kotlin(theme) {
  const fields = semanticTokens.map(key => `    val ${kotlinNames[key]}: Color,`).join("\n");
  const scheme = name => semanticTokens.map(key => `    ${kotlinNames[key]} = Color(0x${theme[name][key]}),`).join("\n");
  return `// Generated by packages/mobile-design/scripts/generate.mjs. Do not edit.
package dev.peppy.mobile.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class PeppyColorScheme(
${fields}
)

object PeppyTokens {
  val Dark = PeppyColorScheme(
${scheme("dark")}
  )
  val Light = PeppyColorScheme(
${scheme("light")}
  )
}
`;
}
function swift(theme) {
  const fields = semanticTokens.map(key => `    let ${swiftNames[key]}: Color`).join("\n");
  const scheme = name => semanticTokens.map(key => `      ${swiftNames[key]}: Color(argb: 0x${theme[name][key]})`).join(",\n");
  return `// Generated by packages/mobile-design/scripts/generate.mjs. Do not edit.
import SwiftUI

struct PeppyColorScheme {
${fields}
}

enum PeppyTokens {
  static let dark = PeppyColorScheme(
${scheme("dark")}
  )
  static let light = PeppyColorScheme(
${scheme("light")}
  )

  static func colors(for colorScheme: ColorScheme) -> PeppyColorScheme {
    colorScheme == .dark ? dark : light
  }
}

private extension Color {
  init(argb: UInt32) {
    self.init(.sRGB, red: Double((argb >> 16) & 0xff) / 255, green: Double((argb >> 8) & 0xff) / 255, blue: Double(argb & 0xff) / 255, opacity: Double((argb >> 24) & 0xff) / 255)
  }
}
`;
}
function androidResourceEscape(value) {
  return value
    .replace(/\\/g, "\\\\")        // Backslash must be escaped first
    .replace(/'/g, "\\'")          // Apostrophe to \'
    .replace(/"/g, '\\"');         // Double quote to \"
}
function xmlEscape(value) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
function androidCopy() { return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by packages/mobile-design/scripts/generate.mjs. Do not edit. -->
<resources>
${Object.entries(nativeCatalog).map(([key, value]) => `    <string name="peppy_${key}">${xmlEscape(androidResourceEscape(value))}</string>`).join("\n")}
</resources>
`; }
function iosCopy() {
  const strings = Object.fromEntries(Object.entries(nativeCatalog).map(([key, value]) => [`peppy.${key}`, { localizations: { en: { stringUnit: { state: "translated", value } } } }]));
  return `${JSON.stringify({ sourceLanguage: "en", strings, version: "1.0" }, null, 2)}\n`;
}
function desktopCopy() {
  const entries = Object.entries(desktopCatalog).map(([key, value]) => `  ${key}: ${JSON.stringify(value)},`).join("\n");
  return `// Generated by packages/mobile-design/scripts/generate.mjs. Do not edit.
export const peppyCopy = {
${entries}
} as const;

export type PeppyCopyKey = keyof typeof peppyCopy;
`;
}
function parseMark(mark) {
  const viewBox = mark.match(/viewBox="([^"]+)"/)?.[1];
  const transform = mark.match(/<path[^>]*transform="([^"]+)"/)?.[1];
  const pathData = mark.match(/<path[^>]*\bd="\s*([\s\S]*?)"\s*\/>/)?.[1].replace(/\s+/g, " ").trim();
  const fill = mark.match(/<path[^>]*\bfill="(#[0-9A-Fa-f]{6})"/)?.[1];
  if (viewBox !== "0 0 512 472" || !transform || !pathData || !fill) throw new Error("Canonical mark is missing its geometry or fill");
  const scale = transform.match(/^scale\(\s*([\d.]+)[ ,]+([\d.]+)\s*\)$/);
  if (!scale) throw new Error("Canonical mark needs a supported two-axis scale transform");
  return { fill, pathData, transform, viewBox, scaleX: Number(scale[1]), scaleY: Number(scale[2]) };
}
function androidVector(mark, tint = mark.fill) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated from packages/mobile-design/assets/peppy-mark.svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="160dp" android:height="148dp" android:viewportWidth="512" android:viewportHeight="472">
    <group android:scaleX="${mark.scaleX}" android:scaleY="${mark.scaleY}">
        <path android:fillColor="${tint}" android:pathData="${mark.pathData}"/>
    </group>
</vector>
`;
}
function launcherForeground(mark, tint = mark.fill) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated from the canonical mark inside Android's 66dp circular safe zone. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    <group android:translateX="22" android:translateY="24.5" android:scaleX="${Number((0.125 * mark.scaleX).toFixed(6))}" android:scaleY="${Number((0.125 * mark.scaleY).toFixed(6))}">
        <path android:fillColor="${tint}" android:pathData="${mark.pathData}"/>
    </group>
</vector>
`;
}
function adaptive() {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated from the canonical Peppy mark. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>
</adaptive-icon>
`;
}
function squareIcon(mark, background, foreground) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
  <rect width="1024" height="1024" fill="${background}"/>
  <g transform="translate(102 140) scale(1.6 1.6)">
    <path fill="${foreground}" transform="${mark.transform}" d="${mark.pathData}"/>
  </g>
</svg>
`;
}
function iosLogoContents() { return `{
  "images" : [ { "filename" : "peppy-logo.svg", "idiom" : "universal", "scale" : "1x" } ],
  "info" : { "author" : "xcode", "version" : 1 }
}
`; }
function iosRootContents() { return `{
  "info" : { "author" : "xcode", "version" : 1 }
}
`; }
function variantName(filename, appearance) { return filename.replace(/\.png$/, `-${appearance}.png`); }
function iosIconContents() {
  const filename = iosDefaultIcons[0];
  const image = (appearance) => ({
    filename: appearance ? variantName(filename, appearance) : filename,
    idiom: "universal", platform: "ios", size: "1024x1024",
    ...(appearance ? { appearances: [{ appearance: "luminosity", value: appearance }] } : {}),
  });
  return `${JSON.stringify({ images: [image(), image("dark"), image("tinted")], info: { author: "xcode", version: 1 } }, null, 2)}\n`;
}

async function outputs() {
  const [css, sourceMark] = await Promise.all([readFile(paths.css, "utf8"), readFile(paths.mark, "utf8")]);
  const mark = parseMark(sourceMark);
  const theme = { dark: selected(extractTheme(css, ":root,")), light: selected(extractTheme(css, ".theme-light")) };
  const icon = squareIcon(mark, "#FFFFFF", mark.fill);
  return new Map([
    [paths.appIcon, icon], [paths.darkAppIcon, squareIcon(mark, "#1A1A1A", theme.dark.brand.replace("FF", "#"))], [paths.tintedAppIcon, squareIcon(mark, "#FFFFFF", "#000000")],
    [paths.androidTokens, kotlin(theme)], [paths.androidStrings, androidCopy()], [paths.androidLogo, androidVector(mark)],
    [paths.androidForeground, launcherForeground(mark)], [paths.androidBackground, `<?xml version="1.0" encoding="utf-8"?>\n<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle"><solid android:color="#FFFFFFFF"/></shape>\n`],
    [paths.androidMonochrome, launcherForeground(mark, "#FF000000")], [paths.androidIcon, adaptive()], [paths.androidRoundIcon, adaptive()],
    [paths.iosRoot, iosRootContents()], [paths.iosTokens, swift(theme)], [paths.iosStrings, iosCopy()], [paths.iosLogo, sourceMark], [paths.iosLogoContents, iosLogoContents()], [paths.iosIconContents, iosIconContents()],
    [paths.desktopCopy, desktopCopy()],
    [paths.desktopLogo, sourceMark], [paths.favicon, sourceMark],
  ]);
}
async function writeOutputs(output) { await Promise.all([...output].map(async ([path, content]) => { await mkdir(dirname(path), { recursive: true }); await writeFile(path, content, "utf8"); })); }
function pngSize(path) { const png = readFileSync(path); return png.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) ? [png.readUInt32BE(16), png.readUInt32BE(20)] : null; }
function verifyIcons() {
  const iosIcons = iosDefaultIcons.flatMap(file => [file, variantName(file, "dark"), variantName(file, "tinted")]);
  for (const file of [...defaultIconFiles.map(file => resolve(iconDir, file)), ...iosIcons.map(file => resolve(iosIconDir, file)), resolve(root, "apps/desktop/public/favicon-32.png")]) if (!existsSync(file)) throw new Error(`Missing generated icon: ${file}`);
  for (const file of [resolve(iconDir, "icon.png"), resolve(iosIconDir, "AppIcon-512@2x.png"), resolve(iosIconDir, variantName("AppIcon-512@2x.png", "dark")), resolve(iosIconDir, variantName("AppIcon-512@2x.png", "tinted"))]) if (pngSize(file)?.join("x") !== (file.includes("icon.png") ? "512x512" : "1024x1024")) throw new Error(`Unexpected icon dimensions: ${file}`);
}
async function generateIcons() {
  execFileSync("pnpm", ["--dir", "apps/desktop", "exec", "tauri", "icon", "../../packages/mobile-design/assets/peppy-app-icon.svg", "--output", "src-tauri/icons", "--fit", "contain", "--ios-color", "#FFFFFF"], { cwd: root, stdio: "inherit" });
  await Promise.all(iosDefaultIcons.map(file => cp(resolve(iconDir, "ios", file), resolve(iosIconDir, file))));
  for (const file of iosDefaultIcons) {
    const [width, height] = pngSize(resolve(iosIconDir, file));
    for (const [appearance, source] of [["dark", paths.darkAppIcon], ["tinted", paths.tintedAppIcon]]) {
      execFileSync("sips", ["-z", String(height), String(width), "-s", "format", "png", source, "--out", resolve(iosIconDir, variantName(file, appearance))], { stdio: "inherit" });
    }
  }
  const current = new Set(iosDefaultIcons.flatMap(file => [file, variantName(file, "dark"), variantName(file, "tinted")]));
  for (const file of await readdir(iosIconDir)) {
    if (file.startsWith("AppIcon-") && file.endsWith(".png") && !current.has(file)) {
      await rm(resolve(iosIconDir, file));
    }
  }
  await cp(resolve(iconDir, "32x32.png"), resolve(root, "apps/desktop/public/favicon-32.png"));
  await rm(resolve(iconDir, "android"), { recursive: true, force: true });
  await rm(resolve(iconDir, "ios"), { recursive: true, force: true });
  for (const file of ["32x32.png", "64x64.png", "StoreLogo.png", ...[30,44,71,89,107,142,150,284,310].map(size => `Square${size}x${size}Logo.png`)]) await rm(resolve(iconDir, file), { force: true });
}
async function main() {
  const output = await outputs();
  if (process.argv.includes("--check")) {
    const stale = [...output].filter(([path, content]) => !existsSync(path) || readFileSync(path, "utf8") !== content).map(([path]) => path);
    if (stale.length) throw new Error(`Generated mobile design files are stale:\n${stale.join("\n")}`);
    verifyIcons();
    return;
  }
  await writeOutputs(output);
  if (process.argv.includes("--icons")) await generateIcons();
}
await main();
