/** Shared native copy. Keys become Android `peppy_*` resources and iOS keys. */
export const catalog = Object.freeze({
  app_name: "Peppy",
  sms: "SMS",
  cancel: "Cancel",
  mirroring: "Mirroring",
  sms_sync: "SMS synchronization",
  wifi_only: "Wi-Fi only",
  skip_silent: "Skip silent notifications",
  media_wifi_only: "Transfer media on Wi-Fi only",
  account: "Account",
  settings: "Settings",
  devices: "Devices",
  pair_device: "Pair a device",
  scan_qr: "Scan pairing QR code",
  use_credential_file: "Use credential file",
  unlock_with_passphrase: "Unlock with passphrase",
  carrier_unavailable: "Carrier messaging is unavailable on this device",
  rcs_unavailable: "RCS is unavailable",
  encrypted: "Device sync encrypted",
  key_mismatch: "Device sync key mismatch",
  not_unlocked: "Device sync not unlocked",
  carrier_not_encrypted: "Carrier SMS/MMS not end-to-end encrypted",
  onboarding_headline: "Welcome to Peppy",
  onboarding_body: "Connect your devices and choose what to sync.",
  onboarding_hosted_cta: "Get started",
  onboarding_hosted_sub: "Peppy Hosted — we run the server for you",
  onboarding_self_hosted_cta: "Use my own server",
  production_hosted_cta: "Use Peppy Hosted",
  production_join_cta: "Join an existing vault",
  production_hosted_unavailable: "Peppy sign-in is unavailable. Try again, or pair with an existing device.",
  production_provider_unconfigured: "Sign-in is not configured for this build.",
  production_signin_failed: "Sign-in could not finish. Try again.",
  production_no_google_account: "Add a Google account in your phone's Settings, then try again.",
  production_session_expired: "Sign in again to manage your Peppy account. Your enrolled device and local data are unchanged.",
  production_billing_open: "Subscribe at peppy.pro",
  production_billing_body: "Choose your plan on Peppy's website. Sign in there with the same account, then return here to continue.",
  production_billing_check: "Check subscription",
  production_billing_pending: "Your subscription is not active yet. Complete setup at peppy.pro, then check again.",
  production_account_mismatch: "This setup belongs to a different Peppy account. Sign in with the original account to resume.",
  production_provision_retry: "Setup could not finish. Try again to resume the same vault safely.",
  production_provision_resume: "Resume vault setup",
  production_create_vault: "Create my vault",
  production_vault_ready: "Your vault is ready",
  production_owner_sas_heading: "Compare verification codes",
  production_pairing_qr_accessibility: "Pairing QR code",
  production_pairing_role_label: "Requested access",
  production_pairing_role_device: "Linked device",
  production_pairing_role_gateway: "Gateway device",
  production_pairing_retry: "Create a new pairing code",
  production_pairing_paused: "Pairing paused. Create a new code to continue.",
  production_pairing_error: "Could not complete pairing. Try a new code.",
  production_existing_vault: "Your account already has a vault. Pair with an enrolled owner device and enter your existing encryption passphrase.",
  production_read_only: "Your hosted vault is read-only. Your saved data is retained; manage your subscription to enable new changes.",
  production_manage_account: "Manage account at peppy.pro",
  production_add_device: "Add another device",
  production_pairing_qr_body: "Scan this code with the device you want to add. Compare the verification code on both devices before approving.",
  production_pairing_waiting: "Waiting for the new device…",
  production_pairing_expired: "This pairing request expired. Create a new one to try again.",
  production_pairing_verify: "I checked that the verification codes match",
  production_pairing_unlocked: "Unlock this owner device before adding another device.",
  production_secure_storage_failed: "Secure storage is unavailable. Setup has stopped to protect your keys and existing data.",
  production_retry_sync: "Retry sync",
  production_network_failed: "Could not reach Peppy. Check your connection and try again.",
  preview_label: "Hosted setup preview — no account is created or payment taken.",
  preview_scenarios: "Preview scenarios",
  preview_reset: "Reset preview",
  preview_error: "This preview step could not be completed. Try again.",
  preview_complete: "Your server preview is ready",
  preview_approval: "Preview another device’s approval",
  preview_continue: "Continue preview",
  hosted_sign_in_headline: "Sign in to Peppy",
  hosted_sign_in_body: "Use the same sign-in method on all your devices.",
  hosted_sign_in_apple: "Continue with Apple",
  hosted_sign_in_google: "Continue with Google",
  hosted_account_checking: "Checking your account…",
  hosted_account_check_failed: "We couldn’t check your account. Try again.",
  hosted_data_preparing: "Preparing your data…",
  hosted_data_prepare_failed: "Preparation couldn’t finish. Try again.",
  hosted_subscribe_headline: "Peppy Hosted",
  hosted_subscribe_body: "Your Peppy server, managed for you.",
  hosted_subscribe_cta: "Subscribe",
  hosted_subscribe_restore: "Restore purchases",
  hosted_subscribe_terms: "Terms",
  hosted_subscribe_privacy: "Privacy",
  hosted_subscribe_legal: "Subscription pricing and renewal details are provided by the store.",
  hosted_subscribe_store_unavailable: "Pricing is unavailable. Try again later.",
  hosted_purchase_pending: "Waiting for purchase approval",
  hosted_purchase_pending_body: "You can return to setup after the store approves the purchase.",
  hosted_purchase_verifying: "Verifying subscription…",
  passphrase_create_headline: "Create your encryption passphrase",
  passphrase_create_body: "This protects your synced content. Enter it yourself when you add another device. It is never sent to Peppy.",
  passphrase_irrecoverable_warn: "Peppy cannot recover this passphrase. Save it somewhere safe.",
  passphrase_generate_cta: "Generate another",
  passphrase_custom_cta: "Write my own",
  passphrase_suggestion_note: "Generated locally on this device",
  passphrase_ack_label: "Peppy cannot recover my passphrase. I have saved it.",
  passphrase_field: "Encryption passphrase",
  passphrase_confirm_headline: "Confirm your encryption passphrase",
  passphrase_confirm_body: "Enter your passphrase again to confirm you saved it.",
  passphrase_confirm_field: "Confirm passphrase",
  passphrase_mismatch: "The passphrases do not match.",
  passphrase_weak: "Use a longer, unpredictable passphrase or the generated suggestion.",
  passphrase_strong: "Ready to use",
  passphrase_show: "Show passphrase",
  passphrase_hide: "Hide passphrase",
  passphrase_copy: "Copy passphrase",
  passphrase_copied: "Copied",
  passphrase_create_submit: "Create my server",
  provisioning_headline: "Setting up your server…",
  provisioning_error: "Setup could not finish. Your subscription is active. Try again to resume.",
  provisioning_ready: "Server ready",
  hosted_join_headline: "Add this phone",
  hosted_join_body: "Compare this code on your other device before approving this phone.",
  hosted_join_waiting: "Waiting for approval…",
  hosted_join_fallback: "Use my encryption passphrase instead",
  hosted_join_denied: "This request was declined or expired. Try again or use your encryption passphrase.",
  device_approval_headline: "Allow this phone?",
  device_approval_body: "Only allow this request if the code matches on your new phone.",
  device_allow: "Allow",
  device_deny: "Deny",
  hosted_unlock_headline: "Enter your encryption passphrase",
  hosted_unlock_body: "Unlock synced content on this phone. Peppy cannot recover your passphrase.",
  hosted_unlock_cta: "Unlock",
  hosted_lapsed_headline: "Your hosted subscription needs attention",
  hosted_lapsed_body: "Renew your subscription to resume hosted sync.",
  hosted_lapsed_resubscribe: "Resubscribe",
  permissions_headline: "Choose what to sync",
  permissions_body: "You can change these choices later in Settings.",
  permissions_contacts: "Contacts",
  permissions_sms: "SMS",
  permissions_notifications: "Notifications",
  permissions_battery: "Background activity",
  permissions_ios_note: "This iPhone supports contact sync. Carrier messaging and notification mirroring are unavailable.",
  permissions_android_note: "Peppy works alongside your default messaging app. SMS and MMS are not end-to-end encrypted by the carrier.",
  permissions_skip: "Set up later",
  permissions_done: "Done",
  self_hosted_headline: "Connect to your own server",
  self_hosted_body: "Scan a pairing QR code from an enrolled owner device, or import a credential file.",
  self_hosted_docs_link: "Self-hosting guide",
  settings_server_section: "Server",
  settings_server_hosted: "Peppy Hosted",
  settings_server_origin: "Server address",
  settings_server_status: "Subscription",
  settings_server_account: "Account",
  settings_server_manage: "Manage subscription",
  settings_server_sign_out: "Sign out",
  settings_server_delete: "Delete account",
  settings_server_delete_title: "Delete your Peppy account?",
  settings_server_delete_body: "Account deletion and subscription cancellation are separate actions. This preview only clears its simulated account.",
  settings_server_active: "Active",
  settings_server_grace: "Payment grace period",
  settings_server_retry: "Payment needs attention",
  settings_server_expired: "Expired",
  settings_server_revoked: "Revoked",
  settings_server_none: "No subscription",
  settings_server_manage_preview: "Subscription management will open the store when Peppy Hosted launches.",
  passphrase_write_custom: "Write my own",
  passphrase_use_generated: "Use generated passphrase",
  settings_server_renew: "Renew subscription",
  continue: "Continue",
  back: "Back",
  try_again: "Try again",
  locked: "Locked",
  setup_provisioning_body: "Creating your vault. This may take a moment.",
  production_add_computer: "Add a computer",
  production_add_computer_scan_body: "Scan the QR code shown on the computer.",
  production_pairing_role_computer: "Computer",
  production_add_computer_origin_mismatch: "This QR code is for a different Peppy server.",
  production_add_computer_already_linked: "This pairing code has already been used. Start pairing again on your computer.",
  production_add_computer_allow_hint: "Connects the computer to your vault.",
  production_add_computer_deny_hint: "Rejects this computer."
});

/** Native catalog: shared catalog excluding preview-only and mobile store keys. */
export const nativeCatalog = Object.freeze(
  Object.fromEntries(
    Object.entries(catalog).filter(([key]) => {
      // Exclude keys prefixed with preview_
      if (key.startsWith("preview_")) return false;
      // Exclude keys suffixed with _preview
      if (key.endsWith("_preview")) return false;
      // Exclude obsolete mobile store/preview-only keys
      const obsoleteKeys = ["settings_server_delete_body", "hosted_subscribe_legal", "hosted_purchase_pending_body", "hosted_subscribe_restore", "settings_server_manage_preview"];
      if (obsoleteKeys.includes(key)) return false;
      return true;
    })
  )
);

/** Desktop wording overrides and desktop-only keys. Mobile outputs use `catalog` only. */
export const desktopOverrides = Object.freeze({
  hosted_join_headline: "Add this computer",
  hosted_join_body: "Compare this code on your other device before approving this computer.",
  device_approval_headline: "Allow this device?",
  device_approval_body: "Only allow this request if the code matches on your new device.",
  hosted_unlock_body: "Unlock synced content on this computer. Peppy cannot recover your passphrase.",
  hosted_unlock_cta: "Unlock securely",
  hosted_subscribe_legal: "Subscription pricing and renewal details are shown at checkout.",
  hosted_subscribe_restore: "I already subscribed",
  hosted_purchase_pending_body: "You can return to setup after checkout completes.",
  passphrase_create_body: "Your encryption passphrase protects your synced content. You will enter the same passphrase on every device. It stays on your devices and is never sent to Peppy.",
  passphrase_ack_label: "Peppy cannot recover my passphrase. I have saved it somewhere safe.",
  passphrase_weak: "Use at least four different, unpredictable words, 24 characters or more.",
  self_hosted_body: "Configure your server address, then import this computer's credential file.",
  passphrase_native_cta: "Enter passphrase securely",
  passphrase_native_note: "A secure system dialog will ask for your passphrase. Peppy's window never sees it.",
  permissions_login: "Open Peppy at login",
  permissions_desktop_note: "These choices are simulated in this preview.",
  hosted_preview_native_only: "This step uses a secure system dialog.",
  setup_mode_hosted: "Peppy Hosted",
  setup_mode_self_hosted: "Self-hosted",
  setup_join_claimed: "A device scanned the code — approve on your phone, then confirm here. If your phone says this computer was already claimed, cancel here.",
  setup_join_confirm: "Continue only if your phone shows this same code.",
  setup_join_approved: "Approved — unlocking…",
  setup_join_continue: "Continue",
  setup_join_retrying: "Reconnecting…",
  setup_self_hosted_join_body: "Enter your server address to scan a QR code from an enrolled owner device.",
  setup_self_hosted_url_hint: "Must start with https://",
  setup_self_hosted_advanced: "Advanced: import credentials",
  setup_choice_existing: "I already use Peppy on my phone",
  setup_choice_existing_hint: "Scan a code with your phone to add this computer.",
  setup_choice_new: "I'm new to Peppy",
  setup_choice_new_hint: "Sign in, choose a plan, and create your vault.",
  setup_join_waiting: "Waiting for your phone to scan…",
  setup_join_scan_hint: "On your enrolled phone, choose Add a computer and scan this code.",
});
export const desktopOnlyKeys = Object.freeze(["passphrase_native_cta", "passphrase_native_note", "permissions_login", "permissions_desktop_note", "hosted_preview_native_only", "setup_mode_hosted", "setup_mode_self_hosted", "setup_join_claimed", "setup_join_confirm", "setup_join_approved", "setup_join_continue", "setup_join_retrying", "setup_self_hosted_join_body", "setup_self_hosted_url_hint", "setup_self_hosted_advanced", "setup_choice_existing", "setup_choice_existing_hint", "setup_choice_new", "setup_choice_new_hint", "setup_join_waiting", "setup_join_scan_hint"]);
export const desktopCatalog = Object.freeze({ ...catalog, ...desktopOverrides });
