[package]
name = "peppy-protocol"
version = "0.1.0"
edition = "2024"
publish = false
default-run = "generate-contracts"

[dependencies]
base64.workspace = true
peppy-domain.workspace = true
schemars = { workspace = true, features = ["uuid1"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true

[[bin]]
name = "generate-contracts"
path = "src/bin/generate-contracts.rs"
