[package]
name = "peppy-crypto"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
hmac.workspace = true
libsodium-rs.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
unicode-normalization = "0.1"
uuid.workspace = true
zeroize.workspace = true
